config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title, :short_description, :language, :price, :level,  presence: true
  validates :description, presence: true, length: { :minimum => 5 }
  
  belongs_to :user
  
  def to_s
    title
  end
  
  has_rich_text :description
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  LANGUAGES = [:"English", :"Hindi", :"Marathi", :"Telugu"]
  def self.languages
    LANGUAGES.map { |language| [language, language] }
  end

  LEVELS = [:"Beginner", :"Intermediate", :"Advanced"]
  def self.levels
    LEVELS.map { |level| [level, level] }
  end
  
  include PublicActivity::Model
  # tracked
  tracked owner: Proc.new{ |controller, model| controller.current_user }
  
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
  
  validates :name, presence: true
  validates_uniqueness_of :name
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  
  rolify
  
  def to_s
    email
  end

  def username
    self.email.split(/@/).first
  end
  
  has_many :courses
  
  
  after_create :assign_default_role

  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:teacher)
      self.add_role(:student)
    else
      self.add_role(:student) if self.roles.blank?
      self.add_role(:teacher) #if you want any user to be able to create own courses
    end
  end

  validate :must_have_a_role, on: :update

  private
  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "Any User must have at least one role!")
    end
  end

end

 # def ensure_login_uniqueness 
  #   if self.login.blank? || User.find_by_login(self.login).count > 0
  #     login_part = self.email.split("@").first
  #     new_login = login_part.dup 
  #     num = 2
  #     while(User.find_by_login(new_login).count > 0)
  #       new_login = "#{login_part}#{num}"
  #       num += 1
  #     end
  #     self.login = new_login
  #   end
  # end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!
  protect_from_forgery
  
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  include PublicActivity::StoreController #save current_user using gem public_activity
  
  before_action :set_global_variables, if: :user_signed_in?
  def set_global_variables
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search) #navbar search
  end
  
  private

  def user_not_authorized #pundit
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    # if params[:title]
    #   @courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive
    # else
    #   # @courses = Course.all
    #   @q = Course.ransack(params[:q])
    #   @courses = @q.result.includes(:user)
    # end
    
    if current_user.has_role?(:admin)
      @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
      @courses = @ransack_courses.result.includes(:user)
    else
      redirect_to root_path, alert: 'You do not have access to the specified resource.'
    end
    
    # @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    # @courses = @ransack_courses.result.includes(:user)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
  end

  # GET /courses/1/edit
  def edit
    authorize @course
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    authorize @course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :price, :language, :level )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @courses = Course.all.limit(3)
    @latest_courses = Course.all.limit(3).order(created_at: :desc)
  end
  
  def activity
    @activities = PublicActivity::Activity.all
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
  
  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to users_path, notice: 'User roles were successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit({role_ids:[]})
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  .card-body
    %small= simple_format(course.short_description)
  .card-footer
    .text-center
      = number_to_currency(course.price)
  .card-footer
    .row
      .col-md-6
        .fa.fa-globe-africa
        = course.language
      .col-md-6
        .text-right
          .fa.fa-signal
          = course.level
  .card-footer
    .row
      .col-md-6
        .far.fa-clock
        = course.created_at.strftime('%d-%b-%Y')
      .col-md-6
        .text-right
          .fa.fa-chalkboard-teacher
          = course.user.username
  // - if policy(course).edit?
  .card-footer
    = link_to 'Show', course, class: 'btn btn-sm btn-primary'
    = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning' 
    = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' 
            

app/views/courses/_form.html.haml
.container
-# frozen_string_literal: true
= simple_form_for @course do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :description, as: :rich_text_area
    %small= f.error :description, class: 'text-danger'
    = f.input :short_description
    // = f.input :language, collection: [ "English", "Hindi", "Telugu", "Marathi", "Bangla" ]
    = f.input :language, collection: Course.languages, include_blank: true
    // = f.input :level, collection: [ "Beginner", "Intermediate", "Advanced" ]
    = f.input :level, collection: Course.levels, include_blank: true
    = f.input :price
    

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
.card
  .card-header
    %h1 Editing course
  .card-body
    = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h3
  .text-center
    Courses
    .badge.badge-info
      = @courses.count
%p

.row
  .col-md-2
    /= search_form_for @q do |f|
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      = f.label :title
      = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'
      = f.label :description
      = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm'
      /= f.search_field :language_cont, placeholder: 'Language', class: 'form-control form-control-sm'
      /= f.select :language_cont, ['English', 'Polish', 'Russian'], include_blank: true, class: 'form-control form-control-sm'
      = f.label :language
      = f.select :language_cont, Course.languages, include_blank: true
      /= f.search_field :level_cont, placeholder: 'Level', class: 'form-control form-control-sm'
      = f.label :level
      = f.select :level_cont, Course.levels, include_blank: true
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
      = f.submit
    = link_to 'refresh', courses_path


  .col-md-10
    .card-columns
      - @courses.each do |course|
        = render 'courses/course', course: course
%br

app/views/courses/new.html.haml
.card
  .card-header
    %h1 New course
  .card-body
    = render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\|
= link_to @course.title, course_path(@course)

%p
= render 'courses/course', course: @course

app/views/home/activity.html.haml
%h3
  .text-center
    Activity
    .badge.badge-info
      = @activities.count
%p

%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      = activity.id
      = activity.trackable_type
      = activity.trackable_id
      = link_to activity.trackable, activity.trackable
      = activity.key
      = activity.parameters
      = activity.owner

app/views/home/index.html.haml
.jumbotron
  .display-4
    What do you want to learn today?
  
  .p-4

  - if current_user
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}
  // .form-inline.my-2.my-lg-0
  //   = form_tag(courses_path, method: :get) do
  //     .input-group
  //       = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
        

.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
      /.fa.fa-brain
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule


%hr
%h2
  Popular Courses
.card-columns
  - @courses.each do |course|
    = render 'courses/course', course: course
%hr
%h2
  Top Rated Courses
.card-columns
  - @courses.each do |course|
    = render 'courses/course', course: course
%hr

%h2
  Latest courses
.card-columns
  - @latest_courses.each do |course|
    = render 'courses/course', course: course

%hr










// %h1 Hello World!!
// %p Find me in app/views/home/index.html.haml


// = link_to root_path, class: 'btn btn-success' do
//   .fa.fa-home
//   Homepage
  

// .br 

// = link_to courses_path, class: 'btn btn-success' do
//   .fa.fa-book
//   Courses

app/views/layouts/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        © 
        = Time.now.year
        Prepare for patent agent exam, 
        .row
        .fa.fa-envelope
        = mail_to 'admin@paep.in'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        // = link_to 'Teach on CoursePlatform', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "/"} PlayaTech
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    // - if current_user && current_user.has_role?(:admin)
    - if current_user 
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-graduation-cap
            Courses
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users

      /SEARCH IN NAVBAR
      = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
        .input-group
          = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
          %span.input-group-append
            %button.btn.btn-primary.btn-sm{:type => "submit"}
              %span.fa.fa-search{"aria-hidden" => "true"}
      /.form-inline.my-2.my-lg-0
      /  = form_tag(courses_path, method: :get) do
      /    .input-group
      /      = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Find a course", class: 'form-control-sm'
      /      %span.input-group-append
      /        %button.btn.btn-primary.btn-sm{:type => "submit"}
      /          %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(home_activity_path)}"}
          = link_to home_activity_path, class: 'nav-link' do
            .fa.fa-bell
            Activity
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.username
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav.mr-auto
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_registration_path)}"}
          = link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_session_path)}"}
          = link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Prepare_for_patent _agent_exam
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
  .container
    %p
    = yield
  %br
  .bg-dark.text-white
    = render 'layouts/footer'
    
    

app/views/users/_user.html.haml
.card
  .card-header
    .fa.fa-user
    = user.email
  .card-footer
    Signed up
    = time_ago_in_words(user.created_at)
    ago
  .card-footer
    %b= 'sign_in_count'.humanize + ":"
    = user.sign_in_count
    .row
    %b= 'current_sign_in_at'.humanize + ":"
    = user.current_sign_in_at
    .row
    %b= 'last_sign_in_at'.humanize + ":"
    = user.last_sign_in_at
    .row
    %b= 'current_sign_in_ip'.humanize + ":"
    = user.current_sign_in_ip
    .row
    %b= 'last_sign_in_ip'.humanize + ":"
    = user.last_sign_in_ip
  .card-footer
    Confirmed email?
    - if user.confirmed_at.present?
      .badge.badge-success Yes
    - else
      .badge.badge-danger No
  .card-footer
    - user.roles.each do |role|
      .badge.badge-info
        = role.name
    - if policy(user).edit?
      = link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-warning'

app/views/users/edit.html.haml
.card
  .card-header
    Editing roles for
    = @user.email
  .card-body
    = simple_form_for @user do |f|
      = f.collection_check_boxes :role_ids, Role.all, :id, :name
      = f.error :roles, class: 'text-danger'
      %hr
      = f.button :submit, class: "btn btn-success"
  .card-footer
    = link_to 'Cancel', users_path, class: 'btn btn-danger'

app/views/users/index.html.haml
%h3
  .text-center
    Users
    .badge.badge-info
      = @users.count
%p

.card-columns
  - @users.each do |user|
    = render 'users/user', user: user
    
.form-inline
  = search_form_for @q do |f|
    = f.search_field :email_cont, placeholder: 'email'
    = f.search_field :sign_in_count_eq, placeholder: 'sign in count'
    = f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign in count'
    = f.submit
  .ml-2
  = link_to 'refresh', users_path

%table.table.table-bordered
  %thead
    %tr
      %th id
      %th= sort_link(@q, :email)
      %th created_at
      %th= 'sign_in_count'.humanize
      %th= 'current_sign_in_at'.humanize
      %th= 'last_sign_in_at'.humanize
      %th= 'current_sign_in_ip'.humanize
      %th= 'last_sign_in_ip'.humanize
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user.created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip